Add animated temporal progress bar
azavea/green-equity-demo pull request #41
Opened 2023-02-28 20:09 UTC by rachelekm

## Overview

Adds an "animated" progress bar and play button to view spending over time.

Closes #24 

### Demo

https://user-images.githubusercontent.com/36374797/221966180-20530ad2-e91c-4ee1-ae46-6b29a4096f2e.mov

### Notes

- This is just a progress bar with the progress values updated as part of a `setInterval` callback, that way there is one constant in state that updates both the progress bar UI and layer colors for that month value so they're as in sync as possible. That value is broken down into 0.2 increments to allow for a more smooth progress bar transition, and the layers will only update colors once the value arrives at a value that correlates with the start of a new month (e.g. whole number)

## Testing Instructions

- `scripts/server`
- Select play button 
- Confirm progress bar updates and colors follow suit over time
- Confirm play button disabled when running
- Confirm reset button displays and can run animation again

 ## Checklist

- [ ] `fixup!` commits have been squashed
- [ ] `CHANGELOG.md` updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [ ] `README.md` updated if necessary to reflect the changes
- [ ] CI passes after rebase

2023-02-28 22:49 UTC, jacobtylerwalls approved these changes
Neat solution.

Missed this in the last review, but I wonder about opening a follow-up card for adding some sort of accessibility feature for the coloring of the states, since it has semantic meaning.

2023-02-28 22:59 UTC, mstone121 requested changes
Working well, but I think we can find a way to simplify how the interval updates. See review comments.

2023-03-01 17:15 UTC, rachelekm commented on src/app/src/components/AnimatedMap.tsx
> +    }, [playButtonDisabled, timeValue, spending]);
Awesome suggestion, thank you! Just implemented your refactor as part of 8112efcca7299ff74a2a73ab986e4dbacdd18763 and popped in a console.log to verify we only have one `setInterval` fired and its appropriately cancelled for each map play. 👍

2023-03-01 17:44 UTC, rachelekm commented
Thanks all for the review! I implemented these fixes and this is set for another look.

> 
> Missed this in the last review, but I wonder about opening a follow-up card for adding some sort of accessibility feature for the coloring of the states, since it has semantic meaning.

Great idea! The above is captured this in issue #44

2023-03-01 17:46 UTC, mstone121 approved these changes
Looks great! Thanks for updating the useEffects.

2023-03-01 17:46 UTC, mstone121 commented on src/app/src/components/AnimatedMap.tsx
> +                setTimeValue(currentTimeValue => Math.round((currentTimeValue + 0.1)*10)/10);
Took me a minute to figure out why this math is necessary. Then I realized:
```js
.1 + .1 + .1 === .30000000000000004 // true
```

2023-03-01 17:51 UTC, rachelekm commented on src/app/src/components/AnimatedMap.tsx
> +                setTimeValue(currentTimeValue => Math.round((currentTimeValue + 0.1)*10)/10);
Bah I know, adding in those smaller increments really help to break down the progress frames and _flow_ like an animation but this line still feels unnecessarily hacky.

2023-03-01 17:52 UTC, merged