Fix category percentages in tooltips, improve agency handling
azavea/green-equity-demo pull request #54
Opened 2023-03-03 19:22 UTC by jacobtylerwalls

## Overview
[Restore CIVIL_WORKS category and improve agency lookup](https://github.com/azavea/green-equity-demo/commit/8667fcaa1fd79ba96b76bcb7d0e435b2e3ca0ec4)
[Make last updated date dynamic](https://github.com/azavea/green-equity-demo/commit/c2c5402db09590db9508d40c951356cae9dec1f9)
[Remove references to announced funding](https://github.com/azavea/green-equity-demo/commit/997d87cf1574a5203154d0579d4e43c6941930ec)
[Create category for all spending](https://github.com/azavea/green-equity-demo/commit/bd88774cee0fbd43846a906f1f32ab96532048db)

Closes #50

### Demo

### Notes
The "all categories" spending wasn't passed to the SpendingTooltip, so the denominator was wrong. Decided to create an ALL categories to track this.

While here, noticed that I didn't implement the dynamic last date updated in #49.

While here, I noticed that some agencies didn't actually exist; they related to "announced" data (which we're not handling), so I validated this against the GSA dashboard and refactored/simplified the agency handling. The sums of the categories are now much closer to 100%.

## Testing Instructions

- update
- server
- View map tooltips

 ## Checklist

- [ ] `fixup!` commits have been squashed
- [ ] `CHANGELOG.md` updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [ ] `README.md` updated if necessary to reflect the changes
- [ ] CI passes after rebase

2023-03-03 20:13 UTC, mstone121 requested changes
Seems like the percentages are off when a category is selected:

<img width="399" alt="Screenshot 2023-03-03 at 2 12 57 PM" src="https://user-images.githubusercontent.com/8356789/222818610-e582c961-cb4f-4e99-a4b3-48fc5af1e7de.png">

2023-03-03 20:18 UTC, jacobtylerwalls commented
Ah, I can't reproduce that. (It's the problem I'm claiming to solve!) I would also figure deleting the old fetched data for good measure would be a good step, as I'd figure things would break without a `lastUpdated.json`.

2023-03-03 20:19 UTC, mstone121 commented
> I would also figure deleting the old fetched data

I had to do this to get the all category data to work. I'll see if I can figure out what's going on.

2023-03-03 20:21 UTC, jacobtylerwalls commented
Just for the sake of comparison, here's my Nebraska with Civil Works selected:

<img width="351" alt="Screenshot 2023-03-03 at 3 21 34 PM" src="https://user-images.githubusercontent.com/38668450/222821221-6e34f93f-fbe4-46d2-a0fe-5fbb131f9fe4.png">

2023-03-03 20:23 UTC, mstone121 commented
Ah, disregard. My branch was out of date. Working now.

2023-03-03 20:38 UTC, mstone121 requested changes
Code looks good, but a couple of request:
- The map markers are no longer changing when the spending category is changed
- Can we update the other sections of the code that use categories to incorporate the `ALL` category?

2023-03-03 22:14 UTC, jacobtylerwalls commented
Good spot. The latest require will require wiping/refetching data again.

2023-03-06 15:30 UTC, mstone121 approved these changes
Looks good and working well.

One small thing which I'll leave up to you if you want to fix or not: Tooltips aren't showing when a state doesn't have a marker. I think this is because the `onAdd` function returns early if there's no spending data, so we could just move the tooltip logic above that.

2023-03-06 16:19 UTC, jacobtylerwalls commented
I think once I address Sophie's feedback from #59 that will actually be the wanted behavior.

2023-03-06 16:24 UTC, mstone121 commented
> I think once I address Sophie's feedback from #59 that will actually be the wanted behavior.

Oh, I didn't see that. #59 can be a separate PR.

2023-03-06 16:51 UTC, merged